#!/bin/bash

docker \
    run \
    --interactive \
    --tty \
    --volume $(workspace):/usr/local/src \
    --workdir /usr/local/src/$(basename $(pwd)) \
    emorymerryman/git-flux:0.0.1 \
    ${@} &&
    true